[workspace]
resolver = "3"
members = ["crates/front","crates/judge", "crates/server","crates/testbox"]

[workspace.dependencies]
clap = "4.5.53"
libc = "0.2.178"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
nix = { version = "0.30.1", features = ["process"] }
tokio = "1.48.0"
reqwest = { version = "0.12.25", features = ["json"] }
salvo = "0.85.0"
eyre = "0.6.12"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
