[workspace]
resolver = "3"
members = ["crates/front", "crates/judge", "crates/server", "crates/shared", "crates/testbox"]

[workspace.dependencies]
clap = "4.5.53"
eyre = "0.6.12"
libc = "0.2.178"
nix = { version = "0.30.1", features = ["process"] }
reqwest = { version = "0.12.25", features = ["json"] }
salvo = "0.85.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
tokio = "1.48.0"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
rust-embed = "8.9.0"
dirs = "6.0.0"
