[package]
name = "front"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.2", features = ["router", "web"] }
eyre.workspace = true
reqwest = { workspace = true }
shared = { path = "../shared" }
web-sys = { version = "0.3.83", features = ["Window"] }

[features]
