[package]
name = "front"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.2", features = ["router", "web"] }
eyre.workspace = true
futures-util.workspace = true
getrandom = { workspace = true, features = ["wasm_js"] }
pharos = "0.5.3"
reqwest = { workspace = true, features = ["cookies"] }
serde.workspace = true
shared = { path = "../shared" }
uuid = { workspace = true, features = ["js"] }
web-sys = { version = "0.3.83", features = ["Window","Storage"] }
ws_stream_wasm = "0.7.5"
serde_json.workspace = true

[features]
independent = []
