[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre.workspace = true
rust-embed = "8.9.0"
salvo = { workspace = true, features = ["serve-static"] }
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber.workspace = true
