[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
dashmap.workspace = true
dirs.workspace = true
eyre.workspace = true
rust-embed.workspace = true
salvo = { workspace = true, features = ["eyre", "serve-static"] }
serde.workspace = true
serde_json.workspace = true
shared = { path = "../shared" }
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
static_init.workspace=true
