[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
serde.workspace = true
uuid.workspace = true
thiserror.workspace = true
compact_str.workspace = true
tracing.workspace = true
